# Generated by Django 2.2 on 2019-04-13 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourney',
            name='notes',
        ),
    ]
