# Generated by Django 2.2 on 2019-04-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0002_remove_tourney_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='heat',
            name='competitors',
            field=models.ManyToManyField(to='tourney.Competitor'),
        ),
    ]
