# Generated by Django 2.2 on 2019-04-14 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tourney', '0004_auto_20190414_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='name',
        ),
        migrations.AddField(
            model_name='competitor',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
